version: '3.9'

services: 
  node-server:
    build: ./
    ports: 
      - 3000:3000
  database:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_DB=cluster
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
